---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 766557868472406017-cPKhwhWiKox04a7YzCztLVAaCsLrYJN
:access_token_secret: 5OuXLfaAazpG6YFeQKDFiHZ2KwSN7x3hh0IUM03nXVDlU
